JanaShop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('user/', include('account.urls')),
    path('products/', include('product.urls')),
    path('cart/', include('cart.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

account/urls.py
from django.urls import path
from product.views import favorites
from . import views

app_name = 'account'
urlpatterns = [
    path('login', views.RegisterOrLogin.as_view(), name='login'),
    path('checkotp', views.CheckOtp.as_view(), name='check_otp'),
    path('logout', views.user_logout, name='logout'),
    path('profile', views.profile, name='profile'),
    path('address_list', views.AddressView.as_view(), name='address_list'),
    path('add/address', views.AddAddressView.as_view(), name='add_address'),
    path('edit_address/<int:pk>', views.EditAddressView.as_view(), name='edit_address'),
    path('set_default/<int:id>', views.Set_default_address.as_view(), name='set_default'),
    path('delete_address/<int:id>', views.delete_address, name='delete_address'),
    path('profile/favorites', favorites, name='favorite_list'),
    path('change_password', views.change_password, name='change_pass'),
    path('change_phone', views.change_phone, name='change_phone'),
    path('edit_profile', views.edit_user, name='change_profile'),
    path('check_new_phone_otp', views.NewPhoneCheckOtp.as_view(), name='check_new_phone_otp'),
    path('resend_code/', views.resend_code, name='resend_code'),
    path('factors', views.factors, name='factors'),
    path('factor-detail/<int:pk>', views.FactorDetailView.as_view(), name='factor_detail'),
]

cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'
urlpatterns = [
    path('', views.CartDetailView.as_view(), name='cart_detail', ),
    path('add/<int:pk>', views.CartAddingView.as_view(), name='cart_add'),
    path('del/<str:id>', views.CartDeleteView.as_view(), name='cart_delete'),
    path('remove', views.cart_removing, name='cart_remove'),
    # path('order/<int:pk>', views.CheckOutView.as_view(), name='checkout'),
    path('order/<int:pk>', views.checkout, name='checkout'),
    path('order/add', views.OrderCreationView.as_view(), name='add_order'),
    path('order/request', views.send_request, name='request'),
    # path('order/verify/<int:pk>', views.VerifyView.as_view(), name='verify'),
    path('order/verify/<int:pk>', views.verify, name='verify'),
    path('order/factor/<int:pk>', views.VerifyDetail.as_view(), name='factor'),
    path('address_list', views.AddressView.as_view(), name='address_list'),
    path('add/address', views.AddAddressView.as_view(), name='add_address'),
    path('edit_address/<int:pk>', views.EditAddressView.as_view(), name='edit_address'),
    path('delete_address/<int:id>', views.delete_address, name='delete_address'),
]

cart/models.py
import uuid

from django.db import models
from account.models import CustomUser, Address
from product.models import Product, Discount


class Order(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, related_name='orders')
    email = models.CharField(max_length=50, null=True, blank=True)
    phone = models.IntegerField(max_length=12)
    total_price = models.BigIntegerField(default=0)
    discount = models.ForeignKey(Discount, null=True, blank=True, on_delete=models.SET_NULL)
    created_time = models.DateTimeField(auto_now_add=True)
    is_paid = models.BooleanField(default=False)
    paid_time = models.DateTimeField(blank=True, null=True)
    address = models.ForeignKey(Address, null=True, blank=True, on_delete=models.CASCADE)

    def get_final_price(self):
        if self.discount and self.discount.is_valid():
            return self.discount.apply_discount(self.total_price)
        return self.total_price



    def __str__(self):
        return f"{self.phone} - {self.id} - {self.created_time}"

    class Meta:
        verbose_name = 'سفارش'
        verbose_name_plural = 'سفارشات'


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='items_p')
    size = models.CharField(max_length=10)
    color = models.CharField(max_length=10)
    quantity = models.SmallIntegerField()
    price = models.PositiveBigIntegerField()

    def get_one_price(self):
        price_per_one = self.price / self.quantity
        return price_per_one

cart/forms.py
from django import forms

from product.models import Discount


class Discount_code(forms.Form):
    code = forms.CharField(
        label='کد تخفیف خود را وارد کنید',
        widget=forms.TextInput(
            attrs={'class': 'form-control', 'placeholder': 'کد تخفیف'}
        )
    )

    def clean_code(self):
        code = self.cleaned_data['code']
        try:
            discount = Discount.objects.get(code=code, is_active=True)
            if not discount.is_valid():
                raise forms.ValidationError("این کد تخفیف منقضی شده است.")
        except Discount.DoesNotExist:
            raise forms.ValidationError("کد تخفیف نامعتبر است.")
        return code

cart/views.py
from django.core.exceptions import ValidationError
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.utils import timezone
from django.views import View
from django.views.generic import UpdateView
from django.contrib import messages

from account.forms import AddressForm
from account.models import Address
from cart.cart_madule import Cart
from cart.forms import Discount_code
from cart.models import Order, OrderItem
from product.models import Product, Discount

from django.conf import settings
import requests
import json


class CartDetailView(View):
    def get(self, request):
        cart = Cart(request)
        return render(request, 'cart/cart.html', {'cart': cart})


class CartAddingView(View):
    def post(self, request, pk):
        product = get_object_or_404(Product, id=pk)
        color, quantity, discount = request.POST.get('color'), request.POST.get(
            'quantity'), product.discount
        cart = Cart(request)
        cart.add(product, quantity, color, discount)
        return redirect('cart:cart_detail')


def cart_removing(request):
    cart = Cart(request)
    cart.remove_cart()
    return redirect('cart:cart_detail')


class CartDeleteView(View):
    def get(self, request, id):
        cart = Cart(request)
        cart.delete(id)
        return redirect('cart:cart_detail')


# class CheckOutView(View):
#     def get(self, request, pk):
#         form = Discount_code()
#         order = get_object_or_404(Order, id=pk)
#         request.session['order_id'] = order.id
#         return render(request, 'cart/checkout.html', {'form': form, 'order': order})
#
#     def post(self, request, pk):
#         form = Discount_code(request.POST)
#         order = get_object_or_404(Order, id=pk)
#         request.session['order_id'] = order.id
#         if form.is_valid():
#             code = form.cleaned_data.get('code')
#             discount = get_object_or_404(Discount, code=code, is_active=True)
#
#             if discount.is_valid() and order.total_price >= discount.min_order_amount:
#                 order.discount = discount
#                 order.total_price = discount.apply_discount(total_amount=order.total_price)
#                 order.save()
#
#         return redirect('cart:checkout', order.id)

def checkout(request, pk):
    form = Discount_code()
    order = Order.objects.last()
    request.session['order_id'] = order.id
    address = request.user.useraddress.get(is_default=True)
    order.address = address
    order.save()

    if request.method == 'POST':
        form = Discount_code(request.POST)
        if form.is_valid():
            code = form.cleaned_data['code']
            discount = Discount.objects.get(code=code)
            order.discount = discount
            order.save()

            messages.success(request, 'کد تخفیف اعمال شد.')

            return redirect('cart:checkout', order.id)



    context = {
        'order': order,
        'form': form,
        'total_price': order.total_price,
        'final_price': order.get_final_price(),
        # 'discount_amount': discount.get_discount_amount(),
    }
    return render(request, 'cart/checkout.html', context)

class OrderCreationView(View):
    def get(self, request):
        cart = Cart(request)
        order = Order.objects.create(user=request.user, phone=request.user.phone, total_price=cart.total_final_price())
        for item in cart:
            OrderItem.objects.create(order=order, product=item['product'], color=item['color']
                                     , price=item['final_price'], quantity=item['quantity'])
        cart.remove_cart()
        return redirect('cart:checkout', str(order.id))


def send_request(request):
    current_order = Order.objects.filter(user=request.user, is_paid=False).last()
    ZARINPAL_CALLBACK_URL = f"http://127.0.0.1:8000/cart/order/verify/{current_order.id}"

    amount = current_order.get_final_price()  # Amount in Toman
    description = "Payment for Test Product"
    email = request.user.email
    mobile = request.user.phone

    headers = {'Content-Type': 'application/json'}
    data = {
        'merchant_id': settings.ZARINPAL_MERCHANT_ID,
        'amount': amount,
        'description': description,
        'callback_url': ZARINPAL_CALLBACK_URL,
        'metadata': {'email': email, 'mobile': mobile}
    }

    try:
        response = requests.post(settings.ZARINPAL_REQUEST_URL, data=json.dumps(data), headers=headers)
        response_data = response.json()
        if response_data['data']['code'] == 100:
            return redirect(f"{settings.ZARINPAL_STARTPAY_URL}{response_data['data']['authority']}")
        else:
            print(response_data['errors']['code'])
            return render(request, 'cart/error.html', {'message': f"Error Code: {response_data['errors']['code']}"})
    except requests.exceptions.RequestException as e:
        print(e)
        return render(request, 'cart/error.html', {'message': str(e)})

def verify(request, pk):
    order = Order.objects.get(id=pk)
    authority = request.GET.get('Authority')
    headers = {'Content-Type': 'application/json'}
    data = {
        'merchant_id': settings.ZARINPAL_MERCHANT_ID,
        'authority': authority,
        'amount': order.get_final_price()  # Same amount as in the request
    }

    try:
        response = requests.post(settings.ZARINPAL_VERIFY_URL, data=json.dumps(data), headers=headers)
        response_data = response.json()
        print(response_data['data']['code'])
        if response_data['data']['code'] == 100:
            for item in order.items.all():
                item.product.sales += 1
                item.product.save()
                item.one_price = item.price / item.quantity
                order.save()

            order.is_paid = True
            order.save()
            return redirect('cart:factor', order.id)
        elif response_data['data']['code'] == 101:
            return render(request, 'cart/error.html', {'message': 'Transaction submitted but not verified.'})
        else:
            return render(request, 'cart/error.html', {'message': f"Transaction failed: {response_data['errors']['code']}"})
    except requests.exceptions.RequestException as e:
        return render(request, 'cart/error.html', {'message': str(e)})

class VerifyDetail(View):
    def get(self, request, pk):
        order = Order.objects.get(id=pk, user=request.user, is_paid=True)

        paid_time = timezone.now()
        order.paid_time = paid_time
        order.save()

        contex = {
            'order': order,
            'paid_time': paid_time,
        }
        return render(request, 'cart/verify.html', contex)

class AddressView(View):
    def get(self, request):
        form = AddressForm()
        addresses = request.user.useraddress.all()
        contex = {
            'form': form,
            "addresses": addresses
        }
        return render(request, 'cart/address_list.html', contex)


# def apply_discount(request, order_id):
#     order = get_object_or_404(Order, id=order_id)
#     form = Discount_code(request.POST or None)
#
#     if request.method == "POST" and form.is_valid():
#         code = form.cleaned_data['code']
#         discount = get_object_or_404(Discount, code=code, active=True)
#
#         if discount.is_valid() and order.total_price >= discount.min_order_amount:
#             order.discount = discount
#             order.save()
#             return redirect("order_summary", order_id=order.id)
#
#     return render(request, "cart/checkout.html", {"form": form, "order": order})

class VerifyView(View):
    def get(self, request, pk):
        order = get_object_or_404(Order, id=pk)

        for item in order.items.all():
            item.product.sales += 1
            item.product.save()

        order.is_paid = True
        order.save()

        return render(request, 'cart/verify.html', {'order': order})

class AddAddressView(View):
    def post(self, request):
        form = AddressForm(request.POST)
        if form.is_valid():
            address = form.save(commit=False)
            address.user = request.user

            if not request.user.useraddress.filter(is_default=True).exists():
                address.is_default = True
            address.save()

        return redirect('cart:address_list')

    def get(self, request):
        form = AddressForm()
        addresses = request.user.useraddress.all()
        contex = {
            'form': form,
            "addresses": addresses
        }
        return render(request, 'cart/add_address.html', contex)

class EditAddressView(UpdateView):
    model = Address
    form_class = AddressForm
    template_name = 'account/edit_address.html'
    success_url = reverse_lazy('cart:address_list')

    def get_queryset(self):
        return Address.objects.filter(user=self.request.user)

def delete_address(request, id):
    address = get_object_or_404(Address, user=request.user, id=id)
    was_default = address.is_default
    address.delete()

    if was_default:
        remain_address = request.user.useraddress.all()
        if remain_address.exists():
            new_default = remain_address.first()
            new_default.is_default = True
            new_default.save()

    return redirect('cart:address_list')

class Set_default_address(View):
    def get(self, request, id):
        address = get_object_or_404(Address, id=id, user=request.user)
        Address.objects.filter(user=request.user).update(is_default=False)
        address.is_default = True
        address.save()
        order_id = request.session['order'].id
        return redirect(reverse('cart:checkout', args=[order_id]))

    def save(self):
        self.get.modified = True

cart/templates/cart/add_address.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
    <section class="inner-page" id="profile-page">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="content">
                        <div class="row">
                            <div class="col-12 col-lg-3">
                                <!-- Side Panel -->
                                {% include 'account/side-panel.html' %}
                                <!-- /Side Panel -->
                            </div>
                            <div class="col-12 col-lg-9 pl-lg-0 pr-lg-2 mt-2 mt-lg-0">
                                <!-- New Address Form -->
                                <div class="custom-container mb-2" id="new-address">
                                    <div class="row pt-2 px-3">
                                        <div class="col-12"><h1>افزودن آدرس جدید</h1></div>
                                    </div>
                                    <hr>
                                    <div class="container">
                                        <div class="row">
                                            <div class="col-12 pt-3">
                                                <form action="{% url 'cart:add_address' %}" method="post">
                                                    {% csrf_token %}
                                                    <div class="row">
                                                        <div class="col-12 col-md-4 pl-2">
                                                            <div class="form-group m-1">
                                                                <label for="province">استان:</label>
                                                                {{ form.state|attr:'class: form-control' }}
                                                            </div>
                                                        </div>
                                                        <div class="col-12 col-md-4 pl-2">
                                                            <div class="form-group m-1">
                                                                <label for="city">استان:</label>
                                                                {{ form.city|attr:'class: form-control' }}
                                                            </div>
                                                        </div>
                                                        <div class="col-12 col-md-8 pl-2">
                                                            <div class="form-group m-1">
                                                                <label for="address">نشانی کامل:</label>
                                                                {{ form.address|attr:'class: form-control' }}
                                                            </div>
                                                        </div>
                                                        <div class="col-12 col-md-4 pl-2">
                                                            <div class="form-group m-1">
                                                                <label for="postal_code">کد پستی:</label>
                                                                {{ form.postal_code|attr:'class: form-control' }}
                                                            </div>
                                                        </div>
                                                        <div id="change" class="col-12 col-md-4 pl-2">
                                                            <div class="form-group m-1">
                                                                <label for="receiver">تحویل گیرنده:</label>
                                                                {{ form.name|attr:'class: form-control' }}
                                                            </div>
                                                        </div>
                                                        <div class="col-12 col-md-4 pl-2">
                                                            <div class="form-group m-1">
                                                                <label for="tel">تلفن تماس:</label>
                                                                {{ form.phone|attr:'class: form-control' }}
                                                            </div>
                                                        </div>
                                                        <div class="col-12">
                                                            <div class="form-group m-1 pb-3">
                                                                <input type="submit"
                                                                       class="btn btn-warning px-5 text-white"
                                                                       value="ذخیره آدرس">
                                                            </div>
                                                        </div>
                                                    </div>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- /New Address Form -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

cart/templates/cart/address_list.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}

{% block content %}
    <section class="inner-page" id="profile-page">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="content">
                        <div class="row">
                            <div class="col-12 col-lg-3">
                                <!-- Side Panel -->
                                {% include 'account/side-panel.html' %}
                                <!-- /Side Panel -->
                            </div>
                            <div class="col-12 col-lg-9 pl-lg-0 pr-lg-2 mt-2 mt-lg-0">

                                <!-- User Addresses -->
                                <div class="custom-container" id="addresses">
                                    <div class="row p-2">
                                        <div class="col-12 col-md-8 my-auto">
                                            <h1>ویرایش نشانی</h1>
                                        </div>

                                        <div class="col-12 col-md-4 text-start text-md-end">
                                            <a href="{% url 'cart:add_address' %}">
                                                <div class="btn btn-outline-dark w-50">
                                                    افزودن آدرس جدید
                                                </div>
                                            </a>
                                        </div>
                                    </div>
                                    <hr>
                                    <div class="container">
                                        <div class="row">
                                            <!-- Address Record -->
                                            {% for add in addresses %}
                                                <div class="col-12 address py-2">
                                                    <div class="row">
                                                        <div class="col-12 col-sm-10">
                                                            <div class="title">{{ add.address }}</div>
                                                            <div class="sub-title">{{ add.state }}، {{ add.city }}</div>
                                                            <div class="sub-title">{{ add.phone }}</div>
                                                            <div class="sub-title">{{ add.name }}</div>
                                                        </div>
                                                        <div class="col-12 col-sm-2 text-lg-end">
                                                            <a href="{% url 'cart:delete_address' add.id %}"
                                                               onclick="return confirm('آیا جهت حذف این آدرس اطمینان دارید؟')"
                                                               class="float-right float-sm-left pr-2 pl-sm-2"><i
                                                                    class="fa fa-trash-alt font-weight-normal"></i></a>
                                                            <a href="{% url 'cart:edit_address' add.id %}"
                                                               class="float-right float-sm-left"><i
                                                                    class="fa fa-edit font-weight-normal"></i></a>
                                                            {% if add.is_default %}
                                                                <a href="{% url 'account:set_default' add.id %}"
                                                                   class="float-right float-sm-left ml-2"
                                                                   title="آدرس پیش فرض"><i class="fa fa-check-circle"
                                                                                           style="color: #fcb941"></i></a>
                                                            {% else %}
                                                                <a href="{% url 'account:set_default' add.id %}"
                                                                   class="float-right float-sm-left ml-2"
                                                                   title="آدرس پیش فرض"><i
                                                                        class="fa fa-circle-notch"></i></a>
                                                            {% endif %}
                                                        </div>
                                                    </div>
                                                </div>
                                            {% endfor %}
                                            <!-- Address Record -->
                                        </div>
                                    </div>
                                </div>
                                <!-- /User Addresses -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}