JanaShop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls')),
    path('user/', include('account.urls')),
    path('products/', include('product.urls')),
    path('cart/', include('cart.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

account/urls.py
from django.urls import path
from product.views import favorites
from . import views

app_name = 'account'
urlpatterns = [
    path('login', views.RegisterOrLogin.as_view(), name='login'),
    path('checkotp', views.CheckOtp.as_view(), name='check_otp'),
    path('logout', views.user_logout, name='logout'),
    path('profile', views.profile, name='profile'),
    path('address_list', views.AddressView.as_view(), name='address_list'),
    path('add/address', views.AddAddressView.as_view(), name='add_address'),
    path('edit_address/<int:pk>', views.EditAddressView.as_view(), name='edit_address'),
    path('set_default/<int:id>', views.Set_default_address.as_view(), name='set_default'),
    path('delete_address/<int:id>', views.delete_address, name='delete_address'),
    path('profile/favorites', favorites, name='favorite_list'),
    path('change_password', views.change_password, name='change_pass'),
    path('change_phone', views.change_phone, name='change_phone'),
    path('edit_profile', views.edit_user, name='change_profile'),
    path('check_new_phone_otp', views.NewPhoneCheckOtp.as_view(), name='check_new_phone_otp'),
    path('resend_code/', views.resend_code, name='resend_code'),
    path('factors', views.factors, name='factors'),
    path('factor-detail/<int:pk>', views.FactorDetailView.as_view(), name='factor_detail'),
]

cart/urls.py
from django.urls import path

from cart import views

app_name = 'cart'
urlpatterns = [
    path('', views.CartDetailView.as_view(), name='cart_detail', ),
    path('add/<int:pk>', views.CartAddingView.as_view(), name='cart_add'),
    path('del/<str:id>', views.CartDeleteView.as_view(), name='cart_delete'),
    path('remove', views.cart_removing, name='cart_remove'),
    # path('order/<int:pk>', views.CheckOutView.as_view(), name='checkout'),
    path('order/<int:pk>', views.checkout, name='checkout'),
    path('order/add', views.OrderCreationView.as_view(), name='add_order'),
    path('order/request', views.send_request, name='request'),
    # path('order/verify/<int:pk>', views.VerifyView.as_view(), name='verify'),
    path('order/verify/<int:pk>', views.verify, name='verify'),
    path('order/factor/<int:pk>', views.VerifyDetail.as_view(), name='factor'),
    path('address_list', views.AddressView.as_view(), name='address_list'),
    path('add/address', views.AddAddressView.as_view(), name='add_address'),
    path('edit_address/<int:pk>', views.EditAddressView.as_view(), name='edit_address'),
    path('delete_address/<int:id>', views.delete_address, name='delete_address'),
]

index/urls.py
from django.urls import path
from . import views

app_name = 'index'
urlpatterns = [
    path('', views.index, name='home'),
    path('faq', views.faq, name='faq'),
    path('about_us', views.about, name='about'),
    path('search', views.search, name='search'),
    path('favorite/add/<int:id>', views.add_to_favorite, name='add_favorite'),
    path('favorite/remove/<int:id>', views.remove_from_favorite, name='delete_favorite'),
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'
urlpatterns = [
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('favorite/add/<int:id>', views.add_to_favorite, name='add_favorite'),
    path('favorite/remove/<int:id>', views.remove_from_favorite, name='delete_favorite'),
    path('list/cat=<slug:slug>', views.product_list, name='product_list'),
    # path('<int:id>/rate/', views.rate, name='rate_product'),
]

templates/includes/categories.html
<div class="droopmenu-nav">
    <div class="droopmenu-nav-wrap">
        <div class="droopmenu-navi">
            <ul class="droopmenu">
                <li class="droopmenu-parent" aria-haspopup="true">
                    <a href="#" aria-expanded="false"><i class="fa fa-bars"></i>&nbsp;&nbsp;دسته بندی کالاها
                        <em class="droopmenu-topanim"></em></a>
                    <div class="dm-arrow"></div>
                    <ul class="droopmenu-grid droopmenu-grid-9">
                        <li class="droopmenu-tabs droopmenu-tabs-vertical">
                            {% for category in categories %}
                                {% if not category.parent %}
                                    <div class="droopmenu-tabsection {% if forloop.first %} droopmenu-tab-active {% endif %} "
                                         id="">
                                        <a class="droopmenu-tabheader" href="#">{{ category.title }}</a>
                                        {% if category.subs.all %}
                                            {% include 'includes/forloop-category.html' %}
                                        {% endif %}
                                    </div>
                                {% endif %}
                            {% endfor %}
                        </li>
                    </ul>
                </li>
                <li><a href="{% url 'index:faq' %}">سوالات متداول<em class="droopmenu-topanim"></em></a>
                <li><a href="{% url 'index:about' %}">درباره ما<em class="droopmenu-topanim"></em></a>
                    {#                <li><a href="">وبلاگ<em class="droopmenu-topanim"></em></a>#}
                    {#                </li>#}
                </li>
            </ul>
        </div>
    </div>
</div>

templates/includes/footer-refrences.html
{% load static %}

<script src="{% static 'js/jquery.min.js' %}"></script>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'plugins/fontawesome/js/all.min.js' %}"></script>
<script src="{% static 'plugins/aos-master/dist/aos.js' %}"></script>
<script src="{% static 'js/droopmenu.js' %}"></script>
<script src="{% static 'js/nouislider.min.js' %}"></script>
<script src="{% static 'js/pagination.js' %}"></script>
<script src="{% static 'js/scripts.js' %}"></script>
<script type="module">


import PhotoSwipeLightbox from '{% static 'node_modules/photoswipe/dist/photoswipe-lightbox.esm.js' %}';
const lightbox = new PhotoSwipeLightbox({
  gallery: '#my-gallery',
  children: 'a',
  pswpModule: () => import('{% static 'node_modules/photoswipe/dist/photoswipe.esm.js' %}')
});
lightbox.init();
</script>

templates/includes/footer.html
{% load static %}

<!-- Footer -->
<section class="pt-4 pb-3" id="footer">
    <div class="container">
        <div class="row">
            <div class="col-6 col-sm-4 col-lg-2">
                <div class="title">دسترسی سریع</div>
                <ul>
                    {#                    <li><a href="./blog.html">بلاگ آموزشی</a></li>#}
                    {#                    <li><a href="./faq.html">راهنمای خرید</a></li>#}
                    {#                    <li><a href="./faq.html">شیوه های پرداخت</a></li>#}
                    {#                    <li><a href="./contact.html">پیگیری سفارش</a></li>#}
                    <li><a href="{% url 'index:faq' %}">سوالات متداول</a></li>
                    <li><a href="{% url 'index:about' %}">درباره ما</a></li>
                </ul>
            </div>
            <div class="col-6 col-sm-4 col-lg-2">
                <div class="title">گروه های محصولات</div>
                <ul>
                    {% for categoty in categories %}
                        {% if not categoty.parent %}
                            <li><a href="{% url 'product:product_list' categoty.slug %}">{{ categoty.title }}</a></li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>
            <div class="col-6 col-sm-4 col-lg-2 d-none d-sm-inline-block">
                <div class="title">ناحیه کاربری</div>
                <ul>
                    <li><a href="{% url 'account:login' %}">عضویت در سایت</a></li>
                    {#                    <li><a href="./reset-password.html">بازیابی رمز عبور</a></li>#}
                    <li><a href="{% url 'cart:cart_detail' %}">سبد خرید</a></li>
                    {#                    <li><a href="./checkout.html">پیش فاکتور</a></li>#}
                </ul>
            </div>
            <div class="col-12 col-md-12 col-lg-6">
                <hr class="d-lg-none">
                <p><img src="{% static 'images/logo.png' %}" alt="">{{ socials.description }} </p>
                <div class="row">
                    <div class="col-12 col-md-6 text-center p-2" id="support-info">
                        <div>7 روز هفته، 24 ساعت شبانه روز</div>
                        <div>پاسخگوی شما هستیم</div>
                        <div>09351234567</div>
                    </div>
                    <div class="col-12 col-md-6 pt-2 pt-md-0" id="certificates">
                        <div class="row">
                            <div class="col-4 text-center">
                                <a href="#"><img src="{% static 'images/certificates/enamad.png' %}" alt=""></a>
                            </div>
                            <div class="col-4 text-center">
                                <a href="#"><img src="{% static 'images/certificates/samandehi.png' %}" alt=""></a>
                            </div>
                            <div class="col-4 text-center">
                                <a href="#"><img src="{% static 'images/certificates/etehadiye.png' %}" alt=""></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- /Footer -->

<!-- Copyright -->
<section class="py-2" id="copyright">
    <div class="container">
        <div class="row">
            <div class="col-12 col-sm-6" id="social-links">
                <span>ما را دنبال کنید</span>

                {% if socials.instagram %}
                    <a href="{{ socials.instagram }}"><img src="{% static 'images/social/insta.png' %}" alt=""></a>{% endif %}
                {% if socials.facebook %}
                    <a href="{{ socials.facebook }}"><img src="{% static 'images/social/facebook.png' %}" alt=""></a>{% endif %}
                {% if socials.linkedin %}
                    <a href="{{ socials.linkedin }}"><img src="{% static 'images/social/linkedin.png' %}" alt=""></a>{% endif %}
                {% if socials.x %}
                    <a href="{{ socials.x }}"><img src="{% static 'images/social/twitter.png' %}" alt=""></a>{% endif %}
                {% if socials.youtube %}
                    <a href="{{ socials.youtube }}"><img src="{% static 'images/social/youtube.png' %}" alt=""></a>
                {% endif %}
            </div>
            <div class="col-12 col-sm-6 text-sm-end pt-2 pt-sm-0">
                <span>کلیه حقوق برای <a href="{% url 'index:home' %}">جاناشاپ</a> محفوظ است.</span>
            </div>
        </div>
    </div>
</section>
<!-- Copyright -->

templates/includes/forloop-category-2.html
{% for category in category.subs.all %}
    <li><a href="{% url 'product:product_list' category.slug %}">{{ category.title }}</a>
{% endfor %}

templates/includes/forloop-category.html
<div class="droopmenu-tabcontent">
    <div class="droopmenu-row">
        {% for category in category.subs.all %}
            <ul class="droopmenu-col droopmenu-col45">
                <li><h4>{{ category.title }}</h4></li>
                {% if category.subs.all %}
                    {% include 'includes/forloop-category-2.html' %}
                {% endif %}

            </ul>
        {% endfor %}

        <ul class="droopmenu-col droopmenu-col4 d-none d-lg-inline-block float-end">
            <li><img
                    src="{{ category.image.url }}"
                    alt="{{ category.title }}"></li>
        </ul>
    </div>
</div>

templates/includes/head-refrences.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>فروشگاه جاناشاپ</title>
    <!-- CSS Styles -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.rtl.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/fontawesome/css/all.min.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/aos-master/dist/aos.css' %}">
    <link rel="stylesheet" href="{% static 'plugins/hover-master/css/hover-min.css' %}">
    <link rel="stylesheet" href="{% static 'css/ionicons.css' %}">
    <link rel="stylesheet" href="{% static 'css/droopmenu.css' %}">
    <link rel="stylesheet" href="{% static 'css/highlight.css' %}">
    <link rel="stylesheet" href="{% static 'css/nouislider.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'node_modules/photoswipe/dist/photoswipe.css' %}">


    <!-- /CSS Styles -->
    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/3b74fce8b8.js" crossorigin="anonymous"></script>
    <script>
        function CustomtoggleDropdown() {
            var dropdown = document.querySelector('.dropdown');
            dropdown.classList.toggle('active');
        }

        // Close the dropdown when clicking outside of it
        document.addEventListener('click', function (event) {
            var dropdown = document.getElementById('dropdown');
            if (!dropdown.contains(event.target)) {
                dropdown.classList.remove('active');
            }
        });
    </script>

</head>

templates/includes/header.html
{% load static %}

<section id="header">
    <!-- Top NavBar -->
    <div id="top-nav">
        <div class="container">
            <div class="row">
                <div class="col-8 d-none d-md-block">
                    <ul>
                        <li><a href="{% url 'index:home' %}">صفحه نخست</a></li>
                        <li><a href="{% url 'index:about' %}">درباره ما</a></li>
{#                        <li><a href="./contact.html">تماس با ما</a></li>#}
                    </ul>
                </div>
                <div class="col-12 col-md-4 text-center text-md-end" id="top-support-info">
                    <span>تلفن مشاوره و فروش: 09334651599</span>
                </div>
            </div>
        </div>
    </div>
    <!-- /Top NavBar -->
    <!-- Search NavBar -->
    <div id="search-nav">
        <div class="container pt-1">
            <div class="row py-3 align-content-center">
                <div class="col-12 col-md-3 col-xl-2 text-center text-md-start pb-2" id="header-logo">
                    <a href="{% url 'index:home' %}">
                        <img src="{% static 'images/logo.png' %}" alt=""> جاناشاپ
                    </a>
                </div>
                <div class="col-12 col-md-5 col-xl-6">
                    <div id="search-bar">
                        <form action="{% url 'index:search' %}">
                            <i class="fa fa-search"></i>
                            <input value="{{ request.GET.q }}" name="q" type="text" placeholder="جستجو کنید...">
                        </form>
                    </div>
                </div>
                <div class="col-12 col-md-4">
                    <div class="row">
                        {% if not user.is_authenticated %}
                            <div class="col-12 col-md-12 col-lg-6 text-center" id="btn-login-register">
                                <a href="{% url 'account:login' %}">ورود/عضویت</a>
                            </div>
                        {% else %}
                            <div style=" z-index: 9999" class="col-12 col-md-12 col-lg-6 text-center " id="btn-login-register">
                                <div class="dropdown" onclick="CustomtoggleDropdown()" id="dropdown">
                                    <button style="outline: none; background: none; border: none"><i
                                            class="fa-solid fa-user fa-lg"
                                            style="color: #FFD43B;"></i>
                                        <a>{{ user.phone }}</a>
                                        <i class="fa-solid fa-angle-down"></i>
                                        <div class="dropdown-content" id="dropdownContent">
                                            <a style="font-size: 15px;" href="{% url 'account:profile' %}">پروفایل
                                                کاربری</a>
                                            <a style="font-size: 15px" href="{% url 'account:favorite_list' %}">علاقه
                                                مندی ها</a>
                                            <a style="font-size: 15px; color: #ff5656"
                                               href="{% url 'account:logout' %}">خروج از حساب</a>
                                        </div>
                                    </button>
                                </div>
                            </div>
                        {% endif %}
                        <div class="col-12 col-md-5 col-lg-6">
                            <a href="{% url 'cart:cart_detail' %}">
                                <div class="btn btn-warning w-100"><i class="fa fa-shopping-cart"></i>&nbsp;<span
                                        class="d-md-none d-lg-inline-block">سبد خرید</span> ({{ cart_count }})
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- /Search NavBar -->
    <!-- Main NavBar -->
    <div id="main-nav">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="droopmenu-navbar dmarrow-down droopmenu-horizontal dmpos-top dmfade">
                        <div class="droopmenu-inner">
                            <div class="droopmenu-header">
                                <a href="#" class="droopmenu-toggle"><i class="dm-burg"></i></a>
                                <span class="d-md-none">منوی فروشگاه</span>
                            </div>
                            <!-- Header Mega Menu-->
                            {% include 'includes/categories.html' %}
                            <!-- /Header Menu Menu -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Main NavBar -->
</section>

templates/includes/mid-banners.html
<div class="container" data-aos="fade-up" data-aos-duration="1200">
    <div class="row">
        <div class="col-12 col-md-4 pt-2 text-center">
            <a href="{{ midbanners.first.link }}">
                <img src="{{ midbanners.first.image }}" alt="">
            </a>
        </div>
        <div class="col-12 col-md-8 pt-2 text-center">
            <a href="{{ midbanners.last.link }}">
                <img src="{{ midbanners.last.image }}" alt="">
            </a>
        </div>
    </div>
</div>

templates/includes/slider-section.html
{% load static %}

<section id="slider" class="mt-3">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-9" data-aos="fade-zoom-in" data-aos-duration="700">
                <div id="carouselExampleCaptions" class="carousel slide carousel-fade" data-bs-ride="carousel">
                    <div class="carousel-indicators">
                        {% for slide in carousel %}
                            <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="{{ forloop.counter0 }}"
                                    class="{% if forloop.first %} active {% endif %}" aria-current="{% if forloop.first %} true {% endif %}"
                                    aria-label="Slide {{ forloop.counter }}"></button>
                        {% endfor %}
                    </div>
                    <div class="carousel-inner">
                        {% for slide in carousel %}
                            <div class="carousel-item {% if forloop.first %} active {% endif %}">
                                <img src="{{ slide.image.url }}" class="d-block" alt="{{ slide.name }}">
                            </div>
                        {% endfor %}
                    </div>
                    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions"
                            data-bs-slide="prev">
                        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Previous</span>
                    </button>
                    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions"
                            data-bs-slide="next">
                        <span class="carousel-control-next-icon" aria-hidden="true"></span>
                        <span class="visually-hidden">Next</span>
                    </button>
                </div>
            </div>
            <div class="col-12 col-md-3 mt-2 mt-sm-1 text-center text-sm-start" id="slider-side-banners">
                <div class="row row-cols-1 row-cols-sm-3 row-cols-md-1 h-100 gy-2 g-sm-1 g-md-0">
                    <div class="col align-self-start" data-aos="fade-top" data-aos-duration="1000">
                        <a href="{{ banners.0.link }}">
                            <img src="{{ banners.0.image }}" alt="" width="100%">
                        </a>
                    </div>
                    <div class="col align-self-center" data-aos="fade-top" data-aos-duration="1100">
                        <a href="{{ banners.1.link }}">
                            <img src="{{ banners.1.image }}" alt="" width="100%">
                        </a>
                    </div>
                    <div class="col align-self-end" data-aos="fade-top" data-aos-duration="1200">
                        <a href="{{ banners.2.link }}">
                            <img src="{{ banners.2.image }}" alt="" width="100%">
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>